// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFBpN1Yfej7TTS3LzSWf2dXFANL4WTDPU',
    appId: '1:361719362630:web:3d1391fd5670b7f1ce4647',
    messagingSenderId: '361719362630',
    projectId: 'deneme-cdda8',
    authDomain: 'deneme-cdda8.firebaseapp.com',
    storageBucket: 'deneme-cdda8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO6e4BdeFIzsKe-q2zcXcqtRXZkqG_QSM',
    appId: '1:361719362630:android:74ddd929a8ac89f3ce4647',
    messagingSenderId: '361719362630',
    projectId: 'deneme-cdda8',
    storageBucket: 'deneme-cdda8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4gkjcKVOh6ky5aH8wWEGT8hsxROEe0Y8',
    appId: '1:361719362630:ios:a280ff1cb6542e8bce4647',
    messagingSenderId: '361719362630',
    projectId: 'deneme-cdda8',
    storageBucket: 'deneme-cdda8.firebasestorage.app',
    iosBundleId: 'com.example.artikSon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4gkjcKVOh6ky5aH8wWEGT8hsxROEe0Y8',
    appId: '1:361719362630:ios:a280ff1cb6542e8bce4647',
    messagingSenderId: '361719362630',
    projectId: 'deneme-cdda8',
    storageBucket: 'deneme-cdda8.firebasestorage.app',
    iosBundleId: 'com.example.artikSon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxIJ97h810_RvRmCZhUhP5YJIY8S1DAZ0',
    appId: '1:361719362630:web:06c065af17ab26c4ce4647',
    messagingSenderId: '361719362630',
    projectId: 'deneme-cdda8',
    authDomain: 'deneme-cdda8.firebaseapp.com',
    storageBucket: 'deneme-cdda8.firebasestorage.app',
  );
}
